[[keishis_sandbox]]
arch = "aarch64"
git-tree-sha1 = "203f676583c98d4322ca1290f0982eb7b90dbc0a"
libc = "glibc"
os = "linux"

    [[keishis_sandbox.download]]
    sha256 = "5ea544f119a4cc58e41b6c0cdbc48857f593c309c042c41bff56b33c7baccc86"
    url = "https://github.com/KeishiS/keishis_sandbox/releases/download/rs-v0.1.3/target-linux-aarch64.tar.gz"
[[keishis_sandbox]]
arch = "x86_64"
git-tree-sha1 = "0fdce297d672762d4b67d44c093e1ea4a4923c16"
os = "macos"

    [[keishis_sandbox.download]]
    sha256 = "6140e9c2f4d6d2c87e11b132868303c26bda760ef195890dd8fd54d02fa8bbfc"
    url = "https://github.com/KeishiS/keishis_sandbox/releases/download/rs-v0.1.3/target-macos-x86_64.tar.gz"
[[keishis_sandbox]]
arch = "aarch64"
git-tree-sha1 = "a2af13d46a0d849cff2bf981a2977d06c97804cf"
os = "macos"

    [[keishis_sandbox.download]]
    sha256 = "ac5a5655b7232b520ecd94eea68f2fe72640f62c582118afea98475f13fcc030"
    url = "https://github.com/KeishiS/keishis_sandbox/releases/download/rs-v0.1.3/target-macos-aarch64.tar.gz"
[[keishis_sandbox]]
arch = "x86_64"
git-tree-sha1 = "11fafaffbc31483026321a58adfa06ece90845f2"
os = "windows"

    [[keishis_sandbox.download]]
    sha256 = "070818d1a2912a5c4475010021253a783a98191ec8d7a3387ee3a2a9fee16191"
    url = "https://github.com/KeishiS/keishis_sandbox/releases/download/rs-v0.1.3/target-windows-x86_64.tar.gz"
[[keishis_sandbox]]
arch = "aarch64"
git-tree-sha1 = "f8a70b1316105dd56d6772acee890e6c7ec0efcd"
os = "windows"

    [[keishis_sandbox.download]]
    sha256 = "13d3a206adbe3c8d81cf56a4fc65982f024f600c8e70f22dfc65fa3276465998"
    url = "https://github.com/KeishiS/keishis_sandbox/releases/download/rs-v0.1.3/target-windows-aarch64.tar.gz"
[[keishis_sandbox]]
arch = "x86_64"
git-tree-sha1 = "cc2abf2b4708b5ff50b350e36d537dcf0cdb1e63"
libc = "glibc"
os = "linux"

    [[keishis_sandbox.download]]
    sha256 = "a6dcf3e1f4eb74f15d7fa08684511c28149974ec275d8fe53fc2bb0bca39e549"
    url = "https://github.com/KeishiS/keishis_sandbox/releases/download/rs-v0.1.3/target-linux-x86_64.tar.gz"
